In [1]:
#importing library
import pandas as pd

#reading the dataset
import pymysql
from sqlalchemy import create_engine

In [2]:
df =pd.read_csv('Walmart.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  object
 2   City            10051 non-null  object
 3   category        10051 non-null  object
 4   unit_price      10020 non-null  object
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  object
 7   time            10051 non-null  object
 8   payment_method  10051 non-null  object
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), object(7)
memory usage: 863.9+ KB

In [4]:
df.duplicated().sum()

np.int64(51)

In [5]:
df.drop_duplicates(inplace= True)

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [8]:
df.fillna(0, inplace= True)

In [9]:
df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [10]:
df.shape

(10000, 11)

In [11]:
#replacing $ sign in unit_price with noting and converting the column into float type

df['unit_price']= df['unit_price'].str.replace('$','').astype(float)

In [12]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10000 non-null  int64
 1   Branch          10000 non-null  object
 2   City            10000 non-null  object
 3   category        10000 non-null  object
 4   unit_price      9969 non-null   float64
 5   quantity        10000 non-null  float64
 6   date            10000 non-null  object
 7   time            10000 non-null  object
 8   payment_method  10000 non-null  object
 9   rating          10000 non-null  float64
 10  profit_margin   10000 non-null  float64
dtypes: float64(4), int64(1), object(6)
memory usage: 937.5+ KB

In [14]:
#creating a new column 'total_price' by multiplying 'unit_price' and 'quantity'
df['total_price']= df['unit_price']* df['quantity']

In [15]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total_price
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [16]:
#mysql connection
engine_mysql = create_engine('mysql+pymysql://root:Adarshsingh%401304@localhost:3306/walmart_db')
 
try:
     engine_mysql
     print("Connection to MySQL database successful!")
except:
   print("connection failed")

Connection to MySQL database successful!

In [17]:
#sending the data into mysql database

df.to_sql(name='walmart', con=engine_mysql, if_exists='append', index= False)

10000